[package]
name = "tasks-war-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tasks-war-bindings = { path = "../tasks-war-bindings" }

# [lib]
# crate-type = ['cdylib']

# [[bin]]
