[package]
name = "tasks-war-website"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1.39", features = ["full"] }
tower = "0.5"
tower-http = { version = "0.5", features = ["fs"] }
serde = "1"
tracing-subscriber = "0.3"
tracing = "0.1" 
tera = "1"



